"""Friday-morning weekly AI summary email.

Generates the same 14-day AI summary as the dashboard, renders it to HTML,
and emails it via Gmail SMTP. Triggered by GitHub Actions on a Friday cron;
can also be run manually with `python scripts/send_weekly_summary_email.py`.

Required environment variables:
  ST_APP_KEY, ST_TENANT_ID, ST_CLIENT_ID, ST_CLIENT_SECRET, DATABASE_URL,
  ANTHROPIC_API_KEY, SMTP_USER, SMTP_PASSWORD, EMAIL_TO,
  EMAIL_FROM (optional; defaults to SMTP_USER)
"""
from __future__ import annotations

import os
import smtplib
import ssl
import sys
from datetime import date
from email.message import EmailMessage

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import markdown as md
from dotenv import load_dotenv

load_dotenv()

from lib.ai_summary import build_summary  # noqa: E402

REQUIRED = (
    "SMTP_USER", "SMTP_PASSWORD", "EMAIL_TO",
    "ST_APP_KEY", "ST_TENANT_ID", "ST_CLIENT_ID", "ST_CLIENT_SECRET",
    "DATABASE_URL", "ANTHROPIC_API_KEY",
)
missing = [k for k in REQUIRED if not os.environ.get(k)]
if missing:
    sys.exit(f"Missing env vars: {', '.join(missing)}")


def main() -> int:
    today = date.today()
    print(f"Building AI summary for {today}…")
    # escape_dollars=False — email clients render markdown without LaTeX munging
    summary_md, brief = build_summary(today, escape_dollars=False, source="weekly_email")
    print(f"Got {len(summary_md)} chars of summary.")

    summary_html = md.markdown(summary_md, extensions=["extra"])
    subject = f"Pure Comfort weekly summary — {today.strftime('%A, %B %d, %Y')}"

    html = f"""<!doctype html>
<html><body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif; color: #111; background: #f6f7f9; margin: 0; padding: 24px;">
  <div style="max-width: 720px; margin: 0 auto; background: #ffffff; border: 1px solid #e3e6ea; border-radius: 8px; padding: 32px;">
    <div style="font-size: 13px; color: #6b7280; margin-bottom: 4px;">Pure Comfort · weekly AI summary</div>
    <div style="font-size: 16px; color: #111; margin-bottom: 20px; font-weight: 600;">{today.strftime('%A, %B %d, %Y')} · last 14 days</div>
    <hr style="border: none; border-top: 1px solid #e3e6ea; margin: 0 0 20px 0;">
    <div style="font-size: 15px; line-height: 1.55;">
      {summary_html}
    </div>
    <hr style="border: none; border-top: 1px solid #e3e6ea; margin: 28px 0 16px 0;">
    <div style="font-size: 12px; color: #888;">
      Generated by Claude Opus 4.7 from the ServiceTitan reporting dashboard. Numbers reconcile to the accountant's P&amp;L within 0.5%. Reply to this email with feedback.
    </div>
  </div>
</body></html>"""

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = os.environ.get("EMAIL_FROM") or os.environ["SMTP_USER"]
    msg["To"] = os.environ["EMAIL_TO"]
    msg.set_content(summary_md + "\n\n---\nGenerated by Claude Opus 4.7 from ServiceTitan reporting.")
    msg.add_alternative(html, subtype="html")

    print(f"Sending to {os.environ['EMAIL_TO']}…")
    with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=ssl.create_default_context()) as smtp:
        smtp.login(os.environ["SMTP_USER"], os.environ["SMTP_PASSWORD"])
        smtp.send_message(msg)
    print("Sent.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
